### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by Tranbook** [k1995/BaiduyunSpider#6]
当我发出搜索请求时，显示的请求链接如下
http://mydomain/s/57un55S15L%2Bd5oqk?from=sf&type=all
可是，在nginx中，每次都是在显示404错误，找不到页面，
这个问题困扰几天了，仍然没解决，
请大佬帮忙解答

**Comment by k1995** [comment]
你Nginx 规则没配对，http://mydomain/index.php/s/57un55S15L%2Bd5oqk?from=sf&type=all这样应该可以访问

**Comment by Tranbook** [comment]
谢谢，我知道问题所在了，Nginx规则少了一句代码，目前404问题已经解决了
